## Preprocessing

In [23]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [24]:
# Drop the non-beneficial ID columns, 'EIN'
application_df = application_df.drop(columns = ["EIN"], axis=1)
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [29]:
name_counts = application_df["NAME"].value_counts()
name_counts[name_counts > 5]

PARENT BOOSTER USA INC                             1260
TOPS CLUB INC                                       765
UNITED STATES BOWLING CONGRESS INC                  700
WASHINGTON STATE UNIVERSITY                         492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC     408
                                                   ...
OLD OAK CLIFF CONSERVATION LEAGUE INC                 6
AMERICAN NEPHROLOGY NURSES ASSOCIATION                6
HUMBLE ISD EDUCATIONAL SUPPORT GROUPS INC             6
PROFESSIONAL LOADMASTER ASSOCIATION                   6
CBMC INC                                              6
Name: NAME, Length: 354, dtype: int64

In [30]:
# Choose a cutoff value and create a list of name counts to be replaced
# use the variable name `names_to_replace`
names_to_replace = list(name_counts[name_counts<=5].index)

# Replace in dataframe
for app in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(app,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                           20043
PARENT BOOSTER USA INC                           1260
TOPS CLUB INC                                     765
UNITED STATES BOWLING CONGRESS INC                700
WASHINGTON STATE UNIVERSITY                       492
                                                ...
HABITAT FOR HUMANITY INTERNATIONAL                  6
DAMAGE PREVENTION COUNCIL OF TEXAS                  6
FLEET RESERVE ASSOCIATION                           6
HUGH OBRIAN YOUTH LEADERSHIP                        6
INTERNATIONAL CONGRESS OF CHURCHES MINISTERS        6
Name: NAME, Length: 355, dtype: int64

In [31]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                       355
APPLICATION_TYPE             9
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [32]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df["APPLICATION_TYPE"].value_counts()
application_counts

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [33]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_counts[application_counts<500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [34]:
# Look at CLASSIFICATION value counts for binning
class_counts = application_df["CLASSIFICATION"].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [35]:

# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts[class_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [36]:
class_counts[class_counts > 10]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
Name: CLASSIFICATION, dtype: int64

In [37]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list (class_counts[class_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [38]:
# Convert categorical data to numeric with `pd.get_dummies`
application_with_dummies_df = pd.get_dummies(application_df)
application_with_dummies_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [39]:
# Split our preprocessed data into our features and target arrays
x = application_with_dummies_df.drop(["IS_SUCCESSFUL"], axis = 1).values
y = application_with_dummies_df["IS_SUCCESSFUL"].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=78)

In [40]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [43]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_feature = len(X_train[0])
hidden_nodes_layers1 = 100
hidden_nodes_layers2 = 30
hidden_nodes_layers3 = 10


nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layers1,
                          input_dim = number_input_feature,
                          activation = "relu")
)


# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layers2,
                          activation = "sigmoid")
)
# third hidden layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layers3,
                          activation = "sigmoid")
)


# Output layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=1,
                          activation = "sigmoid")
)


# Check the structure of the model
nn.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_16 (Dense)            (None, 100)               39900

 dense_17 (Dense)            (None, 30)                3030

 dense_18 (Dense)            (None, 10)                310

 dense_19 (Dense)            (None, 1)                 11

=================================================================
Total params: 43251 (168.95 KB)
Trainable params: 43251 (168.95 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [44]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss = "binary_crossentropy", optimizer="adam", metrics = ["accuracy"])

In [45]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled, y_train, epochs =100)

Epoch 1/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5068 - accuracy: 0.7671
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4443 - accuracy: 0.7950
Epoch 3/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4350 - accuracy: 0.7966
Epoch 4/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4296 - accuracy: 0.7970
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4265 - accuracy: 0.7970
Epoch 6/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4253 - accuracy: 0.7980
Epoch 7/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4235 - accuracy: 0.7991
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4223 - accuracy: 0.7987
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4214 - accuracy: 0.7993
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4203 - accuracy: 0.7994
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4190 - accuracy: 0.8014
Epoch 12/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4186 - accuracy: 0.8015
Epoch 13/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4177 - accuracy: 0.8016
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4171 - accuracy: 0.8023
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4165 - accuracy: 0.8024
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4162 - accuracy: 0.8017
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4151 - accuracy: 0.8021
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4152 - accuracy: 0.8031
Epoch 19/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4146 - accuracy: 0.8018
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4138 - accuracy: 0.8031
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4135 - accuracy: 0.8028
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4133 - accuracy: 0.8032
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4128 - accuracy: 0.8042
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4124 - accuracy: 0.8041
Epoch 25/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4118 - accuracy: 0.8047
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4111 - accuracy: 0.8040
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4109 - accuracy: 0.8046
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4107 - accuracy: 0.8046
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4100 - accuracy: 0.8044
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4097 - accuracy: 0.8048
Epoch 31/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4097 - accuracy: 0.8051
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4094 - accuracy: 0.8040
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4091 - accuracy: 0.8047
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4088 - accuracy: 0.8047
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4091 - accuracy: 0.8054
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4088 - accuracy: 0.8052
Epoch 37/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4082 - accuracy: 0.8065
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4088 - accuracy: 0.8045
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4082 - accuracy: 0.8052
Epoch 40/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4076 - accuracy: 0.8060
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4076 - accuracy: 0.8064
Epoch 42/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4073 - accuracy: 0.8064
Epoch 43/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4070 - accuracy: 0.8064
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4069 - accuracy: 0.8061
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4068 - accuracy: 0.8077
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4068 - accuracy: 0.8072
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4063 - accuracy: 0.8061
Epoch 48/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4062 - accuracy: 0.8065
Epoch 49/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4062 - accuracy: 0.8071
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4061 - accuracy: 0.8070
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4058 - accuracy: 0.8065
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4054 - accuracy: 0.8068
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4052 - accuracy: 0.8080
Epoch 54/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4051 - accuracy: 0.8070
Epoch 55/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4055 - accuracy: 0.8071
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4053 - accuracy: 0.8077
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4055 - accuracy: 0.8069
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4052 - accuracy: 0.8067
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4052 - accuracy: 0.8077
Epoch 60/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4052 - accuracy: 0.8071
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4048 - accuracy: 0.8071
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4044 - accuracy: 0.8091
Epoch 63/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4043 - accuracy: 0.8077
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4045 - accuracy: 0.8078
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4039 - accuracy: 0.8080
Epoch 66/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4041 - accuracy: 0.8079
Epoch 67/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4039 - accuracy: 0.8084
Epoch 68/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4034 - accuracy: 0.8076
Epoch 69/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4039 - accuracy: 0.8078
Epoch 70/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4043 - accuracy: 0.8078
Epoch 71/100
804/804 [==============================] - 4s 4ms/step - loss: 0.4040 - accuracy: 0.8077
Epoch 72/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4046 - accuracy: 0.8088
Epoch 73/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4038 - accuracy: 0.8080
Epoch 74/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4039 - accuracy: 0.8082
Epoch 75/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4037 - accuracy: 0.8074
Epoch 76/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4035 - accuracy: 0.8090
Epoch 77/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4035 - accuracy: 0.8080
Epoch 78/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4033 - accuracy: 0.8078
Epoch 79/100
804/804 [==============================] - 4s 4ms/step - loss: 0.4036 - accuracy: 0.8083
Epoch 80/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4037 - accuracy: 0.8083
Epoch 81/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4039 - accuracy: 0.8079
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4036 - accuracy: 0.8088
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4034 - accuracy: 0.8078
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4030 - accuracy: 0.8080
Epoch 85/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4028 - accuracy: 0.8086
Epoch 86/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4027 - accuracy: 0.8082
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4034 - accuracy: 0.8090
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4026 - accuracy: 0.8096
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4028 - accuracy: 0.8087
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4031 - accuracy: 0.8089
Epoch 91/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4031 - accuracy: 0.8087
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4031 - accuracy: 0.8086
Epoch 93/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4031 - accuracy: 0.8086
Epoch 94/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4024 - accuracy: 0.8093
Epoch 95/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4024 - accuracy: 0.8085
Epoch 96/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4023 - accuracy: 0.8087
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4021 - accuracy: 0.8092
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4027 - accuracy: 0.8084
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4028 - accuracy: 0.8085
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4029 - accuracy: 0.8081

In [46]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.4479 - accuracy: 0.7890 - 534ms/epoch - 2ms/step
Loss: 0.4479031264781952, Accuracy: 0.7890378832817078

In [47]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save("AlphabetSoupCharity_Optimization.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

# The report should contain the following:

# Overview of the analysis: Explain the purpose of this analysis.

# Results: Using bulleted lists and images to support your answers, address the following questions:

# Data Preprocessing

1. What variable(s) are the target(s) for your model?

**Answers** The target variable is  "IS-Successful" column

2. What variable(s) are the features for your model?

**Answers** The features for model are :

APPLICATION_TYPE,	AFFILIATION	,CLASSIFICATION,	USE_CASE, ORGANIZATION,	STATUS,	INCOME_AMT,	SPECIAL_CONSIDERATIONS,	ASK_AMT

3. What variable(s) should be removed from the input data because they are neither targets nor features?

**Answers** EIN(Employee Identification Number), Name

# Compiling, Training, and Evaluating the Model

1. How many neurons, layers, and activation functions did you select for your neural network model, and why?

**Answers** For this model 3 hidden layers each with many neurons because the compute seems to increase the accuracy above 75%. This is expensive . The first activation is "relu" and other layers are "sigmoid". It might boost the accuracy using the functions. Readusting my data that names as get dummies can factor in with better scores.


2. Were you able to achieve the target model performance?

yes

3. What steps did you take in your attempts to increase model performance?
converting the "Name" column in to data points which has the biggest impact on improving efficiency but costly and it requires adding the third layer using "sigmoid" activation function.

# Summary: Summarize the overall results of the deep learning model.
Overall the accuracy is above 75 %. An applicant has a 78% chance of being successful if they follow the below guidelines:

Name of applicants appear more than 5 times.
Type of application following T3, T4, T5, T6, T7, T8, T10, T19
application of following classification



 #Include a recommendation for how a different model could solve this classification problem,
#and then explain your recommendation.

Random Forest Model

In [50]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [51]:
rf_model = RandomForestClassifier(n_estimators=120, random_state=78)

rf_model = rf_model.fit(X_train_scaled, y_train)

y_pred = rf_model.predict(X_test_scaled)

print(f"Random forest model accuracy {accuracy_score(y_test, y_pred)}")

Random forest model accuracy 0.7764431486880466